### ISSUE TITLE
Can you please support for Firefox?

### ISSUE THREAD

**Issue by anishmittal2020** [Eugene-Gubar/YCS#4]
Can you please support for Firefox?

**Comment by Eugene-Gubar** [comment]
This method might work for other chrome extensions that Firefox doesn't have.

1) Download extension YCS on the chrome web store as a zip file
2) Extract the zip file to a folder
3) Install in Firefox click "Debug Add-ons" and then "Load Temporary Add-on…" choose extract folder extension

For this method, the YCS extension will work without an options page.
