### ISSUE TITLE
not working.

### ISSUE THREAD

**Issue by mrxish0t551** [Eugene-Gubar/YCS#7]
hello i've recently downloaded the extension when i try to load comments it doesn't load anything it only loads transcripts

**Comment by Eugene-Gubar** [comment]
@mrxish0t551 
I don’t know yet why it doesn’t work for you.

It always works for me.

Try it. Log out from your YouTube account. Disable other extensions. If you have a VPN, turn it off.

P.s I even tried on different virtual machines and online as well (for example "https://app.any.run/tasks/7e1e5c33-5f6d-4b40-90ae-010c982f27dd") and everything works.

**Comment by mrxish0t551** [comment]
Yup i've fixed it by using a new chrome profile prob something releated to my extensions.

**Comment by Buglardons** [comment]
I have the same problem the extension i tried uninstalling all other extensions but nothing append the only thing that work is disconnecting from youtube but as soon as i relog in the problem reoccur where transcription load but no chat relay or comments. i don't know if i should drop my .har here

**Comment by Eugene-Gubar** [comment]
@Buglardons @mrxish0t551

At the moment, the extension works in incognito mode or when you log out of your YouTube account.
In the next update (to be released today or tomorrow) YCS version 1.0.50 will work fixed.

**Comment by Buglardons** [comment]
Oh ok thanks for the reply !
